USE [master]
GO

/****** Object:  Database [Bundesliga]    Script Date: 05.03.2023 19:00:02 ******/
CREATE DATABASE [Bundesliga]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Bundesliga', FILENAME = N'C:\SQL-Kurs\DB\Bundesliga\Bundesliga.mdf' , SIZE = 10240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 20%)
 LOG ON 
( NAME = N'Bundesliga_log', FILENAME = N'C:\SQL-Kurs\DB\Bundesliga\Bundesliga_log.ldf' , SIZE = 10240KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Bundesliga].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Bundesliga] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Bundesliga] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Bundesliga] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Bundesliga] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Bundesliga] SET ARITHABORT OFF 
GO

ALTER DATABASE [Bundesliga] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Bundesliga] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Bundesliga] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Bundesliga] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Bundesliga] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Bundesliga] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Bundesliga] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Bundesliga] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Bundesliga] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Bundesliga] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Bundesliga] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Bundesliga] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Bundesliga] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Bundesliga] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Bundesliga] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Bundesliga] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Bundesliga] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Bundesliga] SET RECOVERY FULL 
GO

ALTER DATABASE [Bundesliga] SET  MULTI_USER 
GO

ALTER DATABASE [Bundesliga] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Bundesliga] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Bundesliga] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Bundesliga] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Bundesliga] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Bundesliga] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Bundesliga] SET  READ_WRITE 
GO


