USE [Bundesliga]
GO

/****** Object:  Table [dbo].[tb_Wertung]    Script Date: 13.05.2024 21:41:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tb_Wertung](
	[WertungID] [int] IDENTITY(1,1) NOT NULL,
	[Beschreibung] [nvarchar](50) NOT NULL,
	[Punkte] [smallint] NOT NULL,
 CONSTRAINT [PK_tb_Wertung] PRIMARY KEY CLUSTERED 
(
	[WertungID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

