USE [Bundesliga]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [IX_Zeiten]    Script Date: 05.03.2023 19:17:54 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_Zeiten] ON [dbo].[tb_Zeiten]
(
	[Wochentag] ASC,
	[Uhrzeit] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

